//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 03:22:22 AM AEST 
//


package com.chnoumis.seshat.email.xmlmodel.email;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.chnoumis.seshat.email.xmlmodel.email package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Email_QNAME = new QName("http://chnoumis.com/seshat/email/xmlmodel/email", "Email");
    private final static QName _From_QNAME = new QName("http://chnoumis.com/seshat/email/xmlmodel/email", "From");
    private final static QName _To_QNAME = new QName("http://chnoumis.com/seshat/email/xmlmodel/email", "To");
    private final static QName _Cc_QNAME = new QName("http://chnoumis.com/seshat/email/xmlmodel/email", "Cc");
    private final static QName _Bcc_QNAME = new QName("http://chnoumis.com/seshat/email/xmlmodel/email", "Bcc");
    private final static QName _Msg_QNAME = new QName("http://chnoumis.com/seshat/email/xmlmodel/email", "Msg");
    private final static QName _Fields_QNAME = new QName("http://chnoumis.com/seshat/email/xmlmodel/email", "Fields");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.chnoumis.seshat.email.xmlmodel.email
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmailComType }
     * 
     */
    public EmailComType createEmailComType() {
        return new EmailComType();
    }

    /**
     * Create an instance of {@link FromComType }
     * 
     */
    public FromComType createFromComType() {
        return new FromComType();
    }

    /**
     * Create an instance of {@link ToComType }
     * 
     */
    public ToComType createToComType() {
        return new ToComType();
    }

    /**
     * Create an instance of {@link CcComType }
     * 
     */
    public CcComType createCcComType() {
        return new CcComType();
    }

    /**
     * Create an instance of {@link BccComType }
     * 
     */
    public BccComType createBccComType() {
        return new BccComType();
    }

    /**
     * Create an instance of {@link MsgComType }
     * 
     */
    public MsgComType createMsgComType() {
        return new MsgComType();
    }

    /**
     * Create an instance of {@link FieldsComType }
     * 
     */
    public FieldsComType createFieldsComType() {
        return new FieldsComType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmailComType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EmailComType }{@code >}
     */
    @XmlElementDecl(namespace = "http://chnoumis.com/seshat/email/xmlmodel/email", name = "Email")
    public JAXBElement<EmailComType> createEmail(EmailComType value) {
        return new JAXBElement<EmailComType>(_Email_QNAME, EmailComType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FromComType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FromComType }{@code >}
     */
    @XmlElementDecl(namespace = "http://chnoumis.com/seshat/email/xmlmodel/email", name = "From")
    public JAXBElement<FromComType> createFrom(FromComType value) {
        return new JAXBElement<FromComType>(_From_QNAME, FromComType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ToComType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ToComType }{@code >}
     */
    @XmlElementDecl(namespace = "http://chnoumis.com/seshat/email/xmlmodel/email", name = "To")
    public JAXBElement<ToComType> createTo(ToComType value) {
        return new JAXBElement<ToComType>(_To_QNAME, ToComType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CcComType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CcComType }{@code >}
     */
    @XmlElementDecl(namespace = "http://chnoumis.com/seshat/email/xmlmodel/email", name = "Cc")
    public JAXBElement<CcComType> createCc(CcComType value) {
        return new JAXBElement<CcComType>(_Cc_QNAME, CcComType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BccComType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BccComType }{@code >}
     */
    @XmlElementDecl(namespace = "http://chnoumis.com/seshat/email/xmlmodel/email", name = "Bcc")
    public JAXBElement<BccComType> createBcc(BccComType value) {
        return new JAXBElement<BccComType>(_Bcc_QNAME, BccComType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MsgComType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MsgComType }{@code >}
     */
    @XmlElementDecl(namespace = "http://chnoumis.com/seshat/email/xmlmodel/email", name = "Msg")
    public JAXBElement<MsgComType> createMsg(MsgComType value) {
        return new JAXBElement<MsgComType>(_Msg_QNAME, MsgComType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldsComType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FieldsComType }{@code >}
     */
    @XmlElementDecl(namespace = "http://chnoumis.com/seshat/email/xmlmodel/email", name = "Fields")
    public JAXBElement<FieldsComType> createFields(FieldsComType value) {
        return new JAXBElement<FieldsComType>(_Fields_QNAME, FieldsComType.class, null, value);
    }

}
