//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 03:22:22 AM AEST 
//


package com.chnoumis.seshat.email.xmlmodel.tws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.chnoumis.seshat.email.xmlmodel.tws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Request_QNAME = new QName("http://chnoumis.com/seshat/email/xmlmodel/tws", "Request");
    private final static QName _Response_QNAME = new QName("http://chnoumis.com/seshat/email/xmlmodel/tws", "Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.chnoumis.seshat.email.xmlmodel.tws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestComType }
     * 
     */
    public RequestComType createRequestComType() {
        return new RequestComType();
    }

    /**
     * Create an instance of {@link ResponseComType }
     * 
     */
    public ResponseComType createResponseComType() {
        return new ResponseComType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestComType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestComType }{@code >}
     */
    @XmlElementDecl(namespace = "http://chnoumis.com/seshat/email/xmlmodel/tws", name = "Request")
    public JAXBElement<RequestComType> createRequest(RequestComType value) {
        return new JAXBElement<RequestComType>(_Request_QNAME, RequestComType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseComType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResponseComType }{@code >}
     */
    @XmlElementDecl(namespace = "http://chnoumis.com/seshat/email/xmlmodel/tws", name = "Response")
    public JAXBElement<ResponseComType> createResponse(ResponseComType value) {
        return new JAXBElement<ResponseComType>(_Response_QNAME, ResponseComType.class, null, value);
    }

}
